FROM node:22-alpine AS base

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
COPY tooling ./tooling

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @dataflow/web-gui build

EXPOSE 3000

CMD ["pnpm", "--filter", "@dataflow/web-gui", "start"]
